FROM node:18-alpine as builder

WORKDIR /build

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
RUN rm /etc/nginx/conf.d/default.conf
COPY deploy/nginx.conf /etc/nginx/conf.d
COPY --from=builder /build/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]