version: '3.8'
services:
  transportation-app:
    image: transportation-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/build"
      - "/build/node_modules"
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge