FROM node:18-alpine

WORKDIR /build

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=build /build/build/ /usr/share/nginx/html